### ISSUE TITLE
GUI doesn't initialize

### ISSUE THREAD

**Issue by anelson0528** [anelson0528/finance-tracker#10]
Somewhere in the structure updates I forgot to change the initialization so it doesn't work anymore. Needs to be fixed!

 - [x] Fix it.

![image](https://user-images.githubusercontent.com/31452202/46590125-f29f0d00-ca7e-11e8-84be-c3e2eb081e9f.png)

**Comment by anelson0528** [comment]
Made some progress with https://github.com/anelson0528/finance-tracker/commit/428c9067be6f80a6830009db36fba76c33f380a3

But still issues on plotting:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Oak Nelson\finance-tracker\scripts\personalFinances.py", line 117, in <lambda>
    self.plot_Data = ttk.Button(master, text='Show plot', command=lambda: self.plotData())
  File "C:\Users\Oak Nelson\finance-tracker\scripts\personalFinances.py", line 388, in plotData
    plt.plotThedata(filename=self.filename)
  File "C:\Users\Oak Nelson\finance-tracker\scripts\personalFinancesPlot.py", line 129, in plotThedata
    plt.bar(time[-6:], changePos[-6:], 25, alpha=0.5, color='g')
  File "C:\Program Files\Python\Python36-32\lib\site-packages\matplotlib\pyplot.py", line 2667, in bar
    ret = ax.bar(*args, **kwargs)
  File "C:\Program Files\Python\Python36-32\lib\site-packages\matplotlib\__init__.py", line 1845, in inner
    return func(ax, *args, **kwargs)
  File "C:\Program Files\Python\Python36-32\lib\site-packages\matplotlib\axes\_axes.py", line 2219, in bar
    np.atleast_1d(x), height, width, y, linewidth)
  File "C:\Program Files\Python\Python36-32\lib\site-packages\numpy\lib\stride_tricks.py", line 249, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "C:\Program Files\Python\Python36-32\lib\site-packages\numpy\lib\stride_tricks.py", line 184, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by anelson0528** [comment]
Fixed with https://github.com/anelson0528/finance-tracker/commit/45e6471141c39d1b755cbe22fe8e636b39c0bdea
